# Generated by Django 5.1.4 on 2025-03-19 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpenter_work', '0003_alter_carpenterenquire_status'),
        ('organization', '0002_organization_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpenterenquire',
            name='organization_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.organization'),
        ),
    ]
