# Generated by Django 5.1.4 on 2025-03-16 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('registration_number', models.CharField(help_text='Govt registration number', max_length=100, unique=True)),
                ('established_date', models.DateField(blank=True, null=True)),
                ('industry_type', models.CharField(choices=[('TEXTILE', 'Textile'), ('WOOD', 'Wood'), ('PLASTIC', 'Plastic'), ('METAL', 'Metal'), ('FOOD', 'Food Processing'), ('OTHER', 'Other')], max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number1', models.CharField(max_length=15, unique=True)),
                ('phone_number2', models.CharField(max_length=15, unique=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('postal_code', models.CharField(max_length=10)),
                ('gst_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('pan_number', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
