# Generated by Django 5.1.4 on 2025-03-16 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='created_by',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
