# Generated by Django 5.1.4 on 2025-03-18 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0023_process_organization_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
