# Generated by Django 5.1.4 on 2025-03-21 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_organization_created_by'),
        ('process', '0024_alter_process_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='processdetails',
            name='requested_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processmaterials',
            name='organization_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.organization'),
        ),
    ]
