# Generated by Django 5.1.4 on 2025-03-22 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0025_processdetails_requested_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processdetails',
            name='requested_date',
            field=models.DateTimeField(blank=True, help_text='Date and time when the request was made', null=True),
        ),
    ]
