# Generated by Django 5.1.4 on 2025-03-22 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0026_alter_processdetails_requested_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processdetails',
            name='request_accepted_date',
            field=models.DateTimeField(blank=True, help_text='Date and time when the request accepted', null=True),
        ),
    ]
