# Generated by Django 5.1.4 on 2025-03-22 21:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0027_alter_processdetails_request_accepted_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='processdetails',
            name='working_hours',
            field=models.DurationField(default=datetime.timedelta(seconds=28800)),
        ),
    ]
