# Generated by Django 5.1.4 on 2025-03-22 21:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0028_processdetails_working_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processdetails',
            name='working_hours',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
