# Generated by Django 5.1.4 on 2025-03-23 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0029_alter_processdetails_working_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='processdetails',
            name='process_resume_date',
            field=models.DateTimeField(blank=True, help_text='Date and time when the process resume', null=True),
        ),
        migrations.AlterField(
            model_name='processdetails',
            name='process_status',
            field=models.CharField(choices=[('requested', 'Requested'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('Paused', 'Paused'), ('verification', 'Verification'), ('overdue', 'Overdue')], default='requested', help_text='Current status of the process', max_length=20),
        ),
    ]
