# Generated by Django 5.1.4 on 2025-03-28 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0030_processdetails_process_resume_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processdetails',
            name='process_status',
            field=models.CharField(choices=[('requested', 'Requested'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('paused', 'Paused'), ('verification', 'Verification'), ('overdue', 'Overdue')], default='requested', help_text='Current status of the process', max_length=20),
        ),
    ]
