# Generated by Django 5.1.4 on 2025-03-17 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_inventorycategory_organization_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorycategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
