# Generated by Django 5.1.4 on 2025-03-19 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_alter_inventorycategory_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='category',
            new_name='category_id',
        ),
    ]
