# Generated by Django 5.1.4 on 2025-03-16 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0007_alter_customuser_organization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='organization',
            new_name='organization_id',
        ),
    ]
