# Generated by Django 5.1.4 on 2025-03-18 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0031_orderaudio'),
        ('organization', '0002_organization_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='organization_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.organization'),
        ),
    ]
